### ISSUE TITLE
配置好后使用无效，日志没有显示，只运行13秒

### ISSUE THREAD

**Issue by wingswing1** [DemoJ/leigod#1]
RT，能否增加日志显示，可以看哪里出错了吗？

**Comment by DemoJ** [comment]
> RT，能否增加日志显示，可以看哪里出错了吗？

emmmm，我可能知道为什么，最近雷神好像升级了反爬虫，他给拦截返回了一个418错误。我后面看看咋回事吧，，最近忙着玩黑猴可能要段时间。

**Comment by DemoJ** [comment]
> RT，能否增加日志显示，可以看哪里出错了吗？

脚本已更新，可以用了

**Comment by wingswing1** [comment]
> > RT，能否增加日志显示，可以看哪里出错了吗？
> 
> 脚本已更新，可以用了

感谢感谢
